In [3]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
import os
import nibabel as nib

In [5]:
example_ni1 = ('/Users/kushagra/Documents/301 CECT iDose (3).nii.gz')

In [79]:
def get_ras(n1_img_path,point):
	n1_img = nib.load(n1_img_path)
	info = n1_img.affine
	b = np.dot((info).T,point.T)
	n1_header = n1_img.header
	a = np.array([n1_header['qoffset_x'],n1_header['qoffset_y'],n1_header['qoffset_z'],1])
	return a+b

In [80]:
path = '/Users/kushagra/Documents/301 CECT iDose (3).nii.gz'
point = np.array([348,303,71,1])
get_ras(path,point)

array([   -68.03,   -199.36,   1093.07, 127380.3 ])

In [84]:
def get_center(n1_img_path, point1, point2):
	return (get_ras(n1_img_path,point1) + get_ras(n1_img_path,point2))/2
	

In [83]:
def get_sides(n1_img_path, point1, point2):
	return (get_ras(n1_img_path,point1) - get_ras(n1_img_path,point2))

In [93]:
point1 = np.array([119,134,11,1])
point2 = np.array([294,352,159,1])
print(-get_center(path,point1,point2))
print(get_sides(path,point1,point2))

[    -24.28     160.22   -1107.07 -119295.05]
[    114.16     142.21    -148.   -178717.96]


In [102]:
import json
file = open('/Users/kushagra/Desktop/R_1.mrk.json')
data = json.load(file)
data["markups"][0]["center"] = list(-get_center(path,point1,point2))
data["markups"][0]["controlPoints"][0]["position"] = list(-get_center(path,point1,point2))
data["markups"][0]["size"] = list(get_sides(path,point1,point2))
# Save the file with a new name
with open('/Users/kushagra/Desktop/R_1.mrk.json', 'w') as f:
	json.dump(data, f, indent=4)
file.close()
